name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  run-linters:
  
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with: 
          node-version: "14"

      - name: Cache NPM dependencies
        uses: actions/cache@v3 
        id: cache
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}
            
      - name: Install dependencies
        if: ${{ steps.cache.outputs.cache-hit != 'true'}}
        run: npm ci
        
      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true


  build:
  
    needs: run-linters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Build docker image
        run: docker build -t ${{secrets.USERNAME}}/app-js:latest .
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}   
          
          
      - name: Push to docker hub
        run: docker push ${{secrets.USERNAME}}/app-js:latest
        
